#include "gamestate.h"

//TODO FINISH SPLASH SCREEN MENU -- START --OPTIONS --EXIT --GAME OBJECTIVE
//TODO CREATE PAUSE MENU
//TODO CREATE VICTORY SCREEN MENU (RESTART) --NEED ART!
//TODO BALANCE THE GAME!
//TODO CREATE MISSING SOUNDS (UPGRADES) --VICTORY SOUND
//TODO CREATE GAME ICON (APPLICATION ICON)
//TODO SHOW TIME ELAPSED IN MAIN GAME SCREEN
//CHERRY ON TOP --SHOW TOP 5 FASTEST RUNS (STORE RESULTS IN FILE? --PERSISTANCE?)

int main ()
{
	Gamestate level;
	level.SceneManager();
	while (!WindowShouldClose())
	{
		
	}

	return 0;
}